### ISSUE TITLE
KB333 App for call center to retrieve customer information 

### ISSUE THREAD

**Issue by alan2112000** [resumecompanion/customer_support_portal#1]
[Ticket] (https://kb.tarokosoftware.io/?controller=task&action=show&task_id=333&project_id=2)

Sub-Task 

- [x] Fuzzy Search in the Database   #2
- [x] User Authentication  #3
- [x] User Authorization  #4  
- [x] UI View  #5 
- [x] API for Custom Support, RG  and LT   #6   
- [x]  API in lt  resumecompanion/legal_templates#452
- [x]  API in resumecompaion    resumecompanion/resumecompanion#783
- [x] Interface in LT to import the data  #7  
- [x] Capistrano Deployment Script  #8 
- [x] Chef Server Environment Scrip  #9
